// v2 ABI: every recompiled function takes CpuState*. The previous
// hand-curated v1 funcs.h is gone; v2 declarations come from
// funcs_v2.h, regenerated by tools/v2_sync_funcs_h.py.
#pragma once

#include "funcs_v2.h"

// Hand-written non-recompiled bodies still declared here. These are
// not produced by the v2 emit pipeline (no ROM bytes for them) but
// are referenced by recompiled code via funcs.h.
void ResetSpritesFunc(int wh);
void SmwRunOneFrameOfGame_Internal(void);

// Watchdog hook called at every block label (per-block heartbeat).
// Implemented in snesrecomp/runner/src/common_cpu_infra.c; trips a
// 5s frame-timeout via longjmp(g_watchdog_jmp) so tight infinite
// loops don't freeze the runtime indefinitely.
void WatchdogCheck(void);
