#!/usr/bin/env python3
"""Generate src/gen/recomp_func_registry.c from scanned src/gen/*_gen.c bodies.

The registry maps function name -> C function pointer + ROM address + argc.
Used by the L3 execution harness's `invoke_recomp <name>` TCP command so
tests can invoke any recompiled function by name against a captured
savestate and diff the result against the interpreter oracle.

Only sigs we can call through a uniform trampoline are included for MVP:
  void()        argc=0
  void(uint8)   argc=1 — single A-byte input
Other sigs (struct returns, multi-arg, pointer params) are recorded with
argc=-1 so the TCP command can report "unsupported" instead of silently
doing the wrong thing.

Run alongside sync_funcs_h.py after any regen.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GEN_DIR = REPO / 'src' / 'gen'
OUT_PATH = GEN_DIR / 'recomp_func_registry.c'

_GEN_BODY_RE = re.compile(
    r'^(?P<ret>\w[\w\s\*]*?)\s+(?P<name>\w+)\s*\((?P<params>[^)]*)\)\s*\{\s*//\s*(?P<addr>[0-9a-f]{6})',
    re.MULTILINE,
)


def classify_sig(ret_raw: str, params_raw: str) -> int:
    """Return argc for supported sigs, -1 for unsupported.

    Supported MVP:
      void() / void(void)    -> 0
      void(uint8 <name>)     -> 1
    Everything else is unsupported for now (struct returns, multi-arg,
    pointer params, uint16 params, etc.).
    """
    if ret_raw != 'void':
        return -1
    p = params_raw.strip()
    if not p or p == 'void':
        return 0
    parts = [x.strip() for x in p.split(',') if x.strip()]
    if len(parts) == 1 and re.match(r'^uint8\s+\w+$', parts[0]):
        return 1
    return -1


def main() -> int:
    entries = []
    for gen_file in sorted(GEN_DIR.glob('smw_??_gen.c')):
        text = gen_file.read_text()
        for m in _GEN_BODY_RE.finditer(text):
            ret_raw = m.group('ret').strip()
            name = m.group('name')
            params_raw = m.group('params').strip()
            addr = int(m.group('addr'), 16)
            if ret_raw == 'extern' or ret_raw.startswith('static'):
                continue
            argc = classify_sig(ret_raw, params_raw)
            entries.append((name, addr, argc))

    entries.sort(key=lambda e: e[0])

    # Only emit entries for sigs the harness can invoke. Skipped functions
    # wouldn't be callable anyway (argc=-1 means "unsupported" in the
    # invoke_recomp path), and including them forces a forward decl the
    # generator can't reliably produce for multi-arg / struct-return sigs.
    callable_entries = [e for e in entries if e[2] >= 0]

    lines = [
        '// GENERATED by tools/gen_func_registry.py — do not edit.',
        '// Maps recompiled func names to C fn pointers + ROM addrs for the',
        '// L3 execution harness (invoke_recomp TCP command).',
        '',
        '#include <stdint.h>',
        '#include <stddef.h>',
        '#include <string.h>',
        '#include "recomp_func_registry.h"',
        '',
        '// Forward declarations. The registry records one entry per callable',
        '// recompiled function (argc 0 or 1). Multi-arg and struct-return',
        '// sigs are excluded for MVP.',
    ]
    for name, addr, argc in callable_entries:
        if argc == 0:
            lines.append(f'void {name}(void);')
        elif argc == 1:
            lines.append(f'void {name}(uint8_t);')
    lines += [
        '',
        f'#define RECOMP_FUNC_REGISTRY_COUNT {len(callable_entries)}',
        '',
        'const RecompFuncEntry recomp_func_registry[RECOMP_FUNC_REGISTRY_COUNT] = {',
    ]
    for name, addr, argc in callable_entries:
        lines.append(
            f'  {{"{name}", (void*)&{name}, 0x{addr:06x}, {argc}}},'
        )
    lines += [
        '};',
        '',
        'const int recomp_func_registry_count = RECOMP_FUNC_REGISTRY_COUNT;',
        '',
        'const RecompFuncEntry *recomp_func_registry_lookup(const char *name) {',
        '  for (int i = 0; i < RECOMP_FUNC_REGISTRY_COUNT; i++)',
        '    if (strcmp(recomp_func_registry[i].name, name) == 0)',
        '      return &recomp_func_registry[i];',
        '  return NULL;',
        '}',
        '',
    ]

    OUT_PATH.write_text('\n'.join(lines), encoding='utf-8')

    # Sibling header so debug_server can include the type + lookup prototype.
    hdr_lines = [
        '#ifndef RECOMP_FUNC_REGISTRY_H_',
        '#define RECOMP_FUNC_REGISTRY_H_',
        '',
        '#include <stdint.h>',
        '',
        'typedef struct RecompFuncEntry {',
        '  const char *name;',
        '  void *fn;',
        '  uint32_t rom_addr;  // 24-bit ROM address this func was recompiled from',
        '  int argc;           // 0 = void(), 1 = void(uint8), -1 = unsupported sig',
        '} RecompFuncEntry;',
        '',
        'extern const RecompFuncEntry recomp_func_registry[];',
        'extern const int recomp_func_registry_count;',
        '',
        '// Linear scan by name. NULL if not found.',
        'const RecompFuncEntry *recomp_func_registry_lookup(const char *name);',
        '',
        '#endif',
        '',
    ]
    (GEN_DIR / 'recomp_func_registry.h').write_text(
        '\n'.join(hdr_lines), encoding='utf-8')

    supported = len(callable_entries)
    print(f'wrote {supported} callable entries '
          f'({len(entries) - supported} entries with unsupported sigs skipped)')
    print(f'  body: {OUT_PATH.relative_to(REPO)}')
    print(f'  hdr:  {(GEN_DIR / "recomp_func_registry.h").relative_to(REPO)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
